# Generated by Django 5.2 on 2026-08-27 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.CharField(blank=True, help_text='Technician or staff name', max_length=255),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='category',
            field=models.CharField(choices=[('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('STRUCTURAL', 'Structural / Walls'), ('APPLIANCES', 'Appliances'), ('PEST', 'Pest Control'), ('CLEANING', 'Cleaning'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='tenant_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='tenant_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moveoutrequest',
            name='damage_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='moveoutrequest',
            name='deposit_held',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='moveoutrequest',
            name='deposit_refundable',
            field=models.DecimalField(decimal_places=2, default=0, help_text='deposit_held - outstanding_arrears - damage_deductions', max_digits=12),
        ),
        migrations.AddField(
            model_name='moveoutrequest',
            name='insp_cleanliness',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moveoutrequest',
            name='insp_electrical',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moveoutrequest',
            name='insp_flooring',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moveoutrequest',
            name='insp_keys',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moveoutrequest',
            name='insp_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moveoutrequest',
            name='insp_plumbing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moveoutrequest',
            name='insp_walls',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moveoutrequest',
            name='insp_windows',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moveoutrequest',
            name='inspected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moveoutrequest',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moveout_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moveoutrequest',
            name='outstanding_arrears',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total unpaid charges from day 1 of tenancy', max_digits=12),
        ),
        migrations.AddField(
            model_name='moveoutrequest',
            name='rejection_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='deposit_difference',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Positive = tenant must top up. Negative = credit/refund.', max_digits=12),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Last day of current month — new tenancy starts 1st of next month', null=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='new_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='old_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='rejection_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='moveoutrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('INSPECTION', 'Under Inspection'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
