# Generated by Django 5.2 on 2026-08-31 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('portal', '0002_maintenancerequest_assigned_at_and_more'),
        ('properties', '0001_initial'),
        ('tenancies', '0002_moveout_transfer'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transferrequest',
            name='one_pending_transfer_per_tenancy',
        ),
    ]
