# Generated by Django 5.2 on 2026-08-26 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tenancies', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveOut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notice_date', models.DateField()),
                ('moveout_date', models.DateField()),
                ('keys_returned', models.BooleanField(default=False)),
                ('walls_condition', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=20)),
                ('windows_condition', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=20)),
                ('plumbing_condition', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=20)),
                ('electrical_condition', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=20)),
                ('general_condition', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=20)),
                ('inspection_notes', models.TextField(blank=True)),
                ('outstanding_rent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('damage_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_held', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_refundable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_settlement', models.CharField(choices=[('FULL_REFUND', 'Full Refund'), ('PARTIAL_REFUND', 'Partial Refund'), ('NO_REFUND', 'No Refund (damages/arrears)'), ('PENDING', 'Pending Review')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moveouts_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moveouts', to='organizations.organization')),
                ('tenancy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='moveout', to='tenancies.tenancy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moveouts', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Move Out',
                'verbose_name_plural': 'Move Outs',
                'ordering': ['-moveout_date'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_date', models.DateField()),
                ('old_monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_deposit_held', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_deposit_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_difference', models.DecimalField(decimal_places=2, help_text='Positive = tenant owes top-up. Negative = surplus.', max_digits=12)),
                ('outstanding_rent_carried', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_disposition', models.CharField(choices=[('TOPUP', 'Top-up required'), ('REFUND', 'Surplus refunded'), ('RENT_CREDIT', 'Surplus credited to rent'), ('HOLD', 'Surplus held in deposit'), ('EXACT', 'Exact match — no difference')], default='EXACT', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_created', to=settings.AUTH_USER_MODEL)),
                ('new_tenancy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_in', to='tenancies.tenancy')),
                ('old_tenancy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_out', to='tenancies.tenancy')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='organizations.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['-transfer_date'],
            },
        ),
    ]
