# Generated by Django 5.2 on 2026-08-26 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payment_rejection_reason_payment_verified_at_and_more'),
        ('organizations', '0001_initial'),
        ('properties', '0001_initial'),
        ('tenancies', '0002_moveout_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='is_deposit_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='charge_type',
            field=models.CharField(choices=[('RENT', 'Rent'), ('DEPOSIT', 'Deposit'), ('UTILITY', 'Utility'), ('LATE_FEE', 'Late Fee'), ('OTHER', 'Other'), ('OPENING_ARREARS', 'Opening Arrears')], max_length=20),
        ),
        migrations.AlterField(
            model_name='depositmovement',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Signed: positive increases deposit, negative decreases it.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='depositmovement',
            name='movement_type',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('OPENING', 'Opening Balance'), ('DEDUCTION', 'Deduction'), ('REFUND', 'Refund'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('TOPUP', 'Top-up (unit transfer)')], max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('REVERSED', 'Reversed')], default='PENDING_VERIFICATION', max_length=25),
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('STRUCTURAL', 'Structural / Walls'), ('APPLIANCES', 'Appliances'), ('PEST', 'Pest Control'), ('CLEANING', 'Cleaning'), ('OTHER', 'Other')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High — Urgent')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='maintenance_photos/%Y/%m/')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('assigned_to', models.CharField(blank=True, help_text='Technician name or staff name', max_length=255)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('tenant_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tenant_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='organizations.organization')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='tenancies.tenancy')),
            ],
            options={
                'verbose_name': 'Maintenance Request',
                'verbose_name_plural': 'Maintenance Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoveOutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_moveout_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('INSPECTION', 'Under Inspection'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('insp_walls', models.BooleanField(blank=True, null=True)),
                ('insp_plumbing', models.BooleanField(blank=True, null=True)),
                ('insp_electrical', models.BooleanField(blank=True, null=True)),
                ('insp_windows', models.BooleanField(blank=True, null=True)),
                ('insp_flooring', models.BooleanField(blank=True, null=True)),
                ('insp_cleanliness', models.BooleanField(blank=True, null=True)),
                ('insp_keys', models.BooleanField(blank=True, null=True)),
                ('insp_notes', models.TextField(blank=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moveout_inspections', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moveout_requests', to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moveout_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moveout_requests', to='tenancies.tenancy')),
            ],
            options={
                'verbose_name': 'Move-Out Request',
                'verbose_name_plural': 'Move-Out Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True)),
                ('effective_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('deposit_difference', models.DecimalField(decimal_places=2, default=0, help_text='Positive = tenant must top up. Negative = credit.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='organizations.organization')),
                ('requested_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_requests', to='properties.unit')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='tenancies.tenancy')),
            ],
            options={
                'verbose_name': 'Transfer Request',
                'verbose_name_plural': 'Transfer Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('SUBMITTED', 'Proof Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected — Resubmit')], default='PENDING', max_length=20)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='rent_proofs/%Y/%m/')),
                ('proof_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_notices_approved', to=settings.AUTH_USER_MODEL)),
                ('charge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rent_notice', to='finance.charge')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_notices_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_notices', to='organizations.organization')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_notices', to='tenancies.tenancy')),
            ],
            options={
                'verbose_name': 'Rent Notice',
                'verbose_name_plural': 'Rent Notices',
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('tenancy', 'period_start'), name='uniq_rent_notice_tenancy_period')],
            },
        ),
    ]
