# Generated by Django 5.2 on 2026-08-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_charge_is_deposit_charge_payment_proof_of_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moveoutrequest',
            name='inspected_by',
        ),
        migrations.RemoveField(
            model_name='moveoutrequest',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='moveoutrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='moveoutrequest',
            name='tenancy',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='requested_unit',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='tenancy',
        ),
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
        migrations.DeleteModel(
            name='MoveOutRequest',
        ),
        migrations.DeleteModel(
            name='TransferRequest',
        ),
    ]
