# Generated by Django 5.2 on 2026-08-31 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_moveoutrequest_inspected_by_and_more'),
        ('organizations', '0001_initial'),
        ('tenancies', '0002_moveout_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='proof_of_payment',
            field=models.FileField(blank=True, help_text='Upload proof of payment (screenshot, PDF, etc.)', null=True, upload_to='proofs/charges/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='charge',
            name='proof_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='proof_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='charge',
            name='proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='proof_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charge',
            name='proof_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='proof_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_proofs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['tenancy', 'proof_status'], name='finance_cha_tenancy_962618_idx'),
        ),
    ]
