# Generated by Django 5.2 on 2026-08-22 09:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('registration_no', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='org/favicons/')),
                ('footer_text', models.CharField(blank=True, max_length=255)),
                ('theme_primary', models.CharField(default='#1B3A6B', max_length=7)),
                ('theme_secondary', models.CharField(default='#C9A84C', max_length=7)),
                ('theme_accent', models.CharField(default='#2E86AB', max_length=7)),
                ('theme_dark', models.CharField(default='#0D1B2A', max_length=7)),
                ('theme_light', models.CharField(default='#F8F9FA', max_length=7)),
                ('theme_success', models.CharField(default='#28A745', max_length=7)),
                ('theme_warning', models.CharField(default='#FFC107', max_length=7)),
                ('theme_danger', models.CharField(default='#DC3545', max_length=7)),
                ('theme_text_primary', models.CharField(default='#212529', max_length=7)),
                ('theme_text_secondary', models.CharField(default='#6C757D', max_length=7)),
                ('theme_border', models.CharField(default='#DEE2E6', max_length=7)),
                ('receipt_size', models.CharField(choices=[('MM80', '80mm Thermal'), ('MM58', '58mm Thermal'), ('MOBILE', 'Mobile PDF')], default='MM80', max_length=10)),
                ('cutover_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
    ]
