from datetime import date
from django import forms
from tenants.models import Tenant
from tenancies.models import Tenancy
from .models import Payment, Charge, Adjustment


class PaymentForm(forms.Form):
    """
    Record a payment against a tenant. Allocation is automatic
    (oldest charge first); an optional deposit portion is kept separate.
    """
    tenant = forms.ModelChoiceField(
        queryset=Tenant.objects.none(),
        widget=forms.Select(attrs={'class': 'rw-select'}),
    )
    amount = forms.DecimalField(
        max_digits=12, decimal_places=2, min_value=0.01,
        widget=forms.NumberInput(attrs={'class': 'rw-input', 'placeholder': '0.00'}),
    )
    payment_date = forms.DateField(
        initial=date.today,
        widget=forms.DateInput(attrs={'class': 'rw-input', 'type': 'date'}),
    )
    method = forms.ChoiceField(
        choices=Payment.Method.choices,
        widget=forms.Select(attrs={'class': 'rw-select'}),
    )
    reference = forms.CharField(
        required=False, max_length=64,
        widget=forms.TextInput(attrs={'class': 'rw-input',
                                      'placeholder': 'M-Pesa / bank code'}),
    )
    deposit_amount = forms.DecimalField(
        required=False, max_digits=12, decimal_places=2, min_value=0, initial=0,
        widget=forms.NumberInput(attrs={'class': 'rw-input', 'placeholder': '0.00'}),
    )
    notes = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'class': 'rw-textarea', 'rows': 2}),
    )

    def __init__(self, *args, organization=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.organization = organization
        if organization is not None:
            self.fields['tenant'].queryset = Tenant.objects.filter(
                organization=organization, status=Tenant.Status.ACTIVE,
            ).order_by('full_name')

    def clean(self):
        cleaned = super().clean()
        amount = cleaned.get('amount') or 0
        deposit = cleaned.get('deposit_amount') or 0
        if deposit and deposit > amount:
            self.add_error('deposit_amount',
                           'Deposit portion cannot exceed the payment amount.')
        return cleaned


class ChargeForm(forms.ModelForm):
    """Add a manual (non-rent) charge to a tenancy."""

    class Meta:
        model = Charge
        fields = ['charge_type', 'description', 'amount', 'due_date']
        widgets = {
            'charge_type': forms.Select(attrs={'class': 'rw-select'}),
            'description': forms.TextInput(attrs={'class': 'rw-input',
                                                  'placeholder': 'e.g. Water — August'}),
            'amount':      forms.NumberInput(attrs={'class': 'rw-input', 'placeholder': '0.00'}),
            'due_date':    forms.DateInput(attrs={'class': 'rw-input', 'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Rent charges are generated by the system, not added manually.
        self.fields['charge_type'].choices = [
            (v, l) for v, l in Charge.Type.choices if v != Charge.Type.RENT
        ]


class AdjustmentForm(forms.ModelForm):

    class Meta:
        model = Adjustment
        fields = ['direction', 'amount', 'reason', 'effective_date']
        widgets = {
            'direction':      forms.Select(attrs={'class': 'rw-select'}),
            'amount':         forms.NumberInput(attrs={'class': 'rw-input', 'placeholder': '0.00'}),
            'reason':         forms.Textarea(attrs={'class': 'rw-textarea', 'rows': 2}),
            'effective_date': forms.DateInput(attrs={'class': 'rw-input', 'type': 'date'}),
        }


class GenerateRentForm(forms.Form):
    MONTHS = [(i, date(2000, i, 1).strftime('%B')) for i in range(1, 13)]

    year = forms.IntegerField(
        min_value=2000, max_value=2100,
        widget=forms.NumberInput(attrs={'class': 'rw-input'}),
    )
    month = forms.ChoiceField(
        choices=MONTHS,
        widget=forms.Select(attrs={'class': 'rw-select'}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        today = date.today()
        self.fields['year'].initial = today.year
        self.fields['month'].initial = today.month


class VerifyPaymentForm(forms.Form):
    """Financial-PIN gate for payment verification (spec §20)."""

    pin = forms.CharField(
        label='Your Financial PIN',
        widget=forms.PasswordInput(attrs={
            'class': 'rw-input', 'inputmode': 'numeric',
            'placeholder': 'Enter your PIN', 'autocomplete': 'off'}),
    )
    deposit_amount = forms.DecimalField(
        required=False, max_digits=12, decimal_places=2, min_value=0, initial=0,
        widget=forms.NumberInput(attrs={'class': 'rw-input', 'placeholder': '0.00'}),
    )


class RejectPaymentForm(forms.Form):
    reason = forms.CharField(
        widget=forms.Textarea(attrs={
            'class': 'rw-textarea', 'rows': 3,
            'placeholder': 'Why is this claim being rejected?'}),
    )
