# Generated by Django 5.2 on 2026-08-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('RENT_DUE', 'Rent Due'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_VERIFIED', 'Payment Verified'), ('PAYMENT_REJECTED', 'Payment Rejected'), ('MAINTENANCE_UPDATE', 'Maintenance Update'), ('MOVEOUT_UPDATE', 'Move-Out Update'), ('TRANSFER_UPDATE', 'Transfer Update'), ('GENERAL', 'General')], default='GENERAL', max_length=30),
        ),
    ]
